### ISSUE TITLE
white input

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Matthew-Smith/neon-slack#6]
![screen shot 2016-12-08 at 12 11 41](https://cloud.githubusercontent.com/assets/3514015/21004061/8e16a832-bd3f-11e6-9c96-ff3b7498eb57.png)

looks like your `!important` do not works against inline `!important`

**Comment by TTy32** [comment]
![image](https://cloud.githubusercontent.com/assets/732155/21005094/b9df4d2c-bd33-11e6-93e6-cc0b0815fb42.png)

Seems to work on my end, tested with Firefox / Chrome (most recent version). Are you sure you're using the most recent style? Which OS / browser did you tested with?

**Comment by vitaly-zdanevich** [comment]
The most recent style, Chrome 55.0.2883.95 (64-bit)

**Comment by midnightlynx** [comment]
I'm having this problem too.
Chrome 57.0.2987.98 (64-bit)
Latest version of the style. I even removed and reinstalled it to make sure.

Message boxes also go to a white background on hover, as shown below.

![slack-style](https://cloud.githubusercontent.com/assets/7332681/23910573/70b812f0-0897-11e7-96fa-d1de52730b0c.jpg)

**Comment by TTy32** [comment]
Was able to reproduce it now. Created two pull requests that should fix this for both the glow and no-glow versions.

Thanks for reporting.
