### ISSUE TITLE
Message text broke

### ISSUE THREAD

**Issue by midnightlynx** [Matthew-Smith/neon-slack#9]
Something changed on Slack's end, and now the body text of slack messages is dark, making it hard to read over the dark background.

**Comment by Matthew-Smith** [comment]
I updated the style and so it should be usable again. The main chat stuff is fixed but I will need to update some of the popups and other menus before it is completely done!

**Comment by Matthew-Smith** [comment]
I updated the style and so it should be usable again. The main chat stuff is fixed but I will need to update some of the popups and other menus before it is completely done!
